export type ADD_PLACE = 'ADD_PLACE';
export const ADD_PLACE: ADD_PLACE = 'ADD_PLACE';

export type DELETE_PLACE = 'DELETE_PLACE';
export const DELETE_PLACE: DELETE_PLACE = 'DELETE_PLACE';

export type SELECT_PLACE = 'SELECT_PLACE';
export const SELECT_PLACE: SELECT_PLACE = 'SELECT_PLACE';

export type DESELECT_PLACE = 'DESELECT_PLACE';
export const DESELECT_PLACE: DESELECT_PLACE = 'DESELECT_PLACE';